import { CustomFields, LanguageCode } from '@vendure/core';

export const aridaCatalogCustomFields: CustomFields = {
    Order: [
        {
            name: 'recipientFullName',
            type: 'string',
            nullable: true,
            public: true,
            label: [{ languageCode: LanguageCode.en, value: 'Recipient full name' }],
        },
        {
            name: 'recipientPhoneNumber',
            type: 'string',
            nullable: true,
            public: true,
            label: [{ languageCode: LanguageCode.en, value: 'Recipient phone number' }],
        },
    ],
    Product: [
        { name: 'vendorName', type: 'string', nullable: true, public: true },
        { name: 'sourceUrl', type: 'string', length: 1024, nullable: true, public: false },
        { name: 'sourceProductId', type: 'string', nullable: true, public: false },
        { name: 'rawCharacteristicsJson', type: 'text', nullable: true, public: false },
        { name: 'packageCount', type: 'int', nullable: true, public: true },
        { name: 'warrantyMonths', type: 'int', nullable: true, public: true },
        { name: 'weightKg', type: 'float', nullable: true, public: true },
        { name: 'volumeM3', type: 'float', nullable: true, public: true },
        { name: 'dimensionsMm', type: 'text', nullable: true, public: true },
        { name: 'includedItems', type: 'text', nullable: true, public: true },
        { name: 'decor', type: 'text', nullable: true, public: true },
        { name: 'additionalInfo', type: 'text', nullable: true, public: true },
        { name: 'packagingNotes', type: 'text', nullable: true, public: true },
        { name: 'maxLoadKg', type: 'float', nullable: true, public: true },
        { name: 'minimumDoorWidthCm', type: 'float', nullable: true, public: true },
        { name: 'frameMaterialText', type: 'text', nullable: true, public: true },
        { name: 'facadeMaterialText', type: 'text', nullable: true, public: true },
        { name: 'edgeMaterialText', type: 'text', nullable: true, public: true },
        { name: 'shelfMaterialText', type: 'text', nullable: true, public: true },
        { name: 'hardwareText', type: 'text', nullable: true, public: true },
        { name: 'frontHardwareText', type: 'text', nullable: true, public: true },
        { name: 'drawerMaterialText', type: 'text', nullable: true, public: true },
        { name: 'countertopMaterialText', type: 'text', nullable: true, public: true },
        { name: 'upholsteryText', type: 'text', nullable: true, public: true },
        { name: 'kitchenShape', type: 'string', nullable: true, public: true },
        { name: 'kitchenElements', type: 'text', nullable: true, public: true },
        { name: 'countertopDimensionsMm', type: 'text', nullable: true, public: true },
        { name: 'bedDimensionsMm', type: 'text', nullable: true, public: true },
        { name: 'recommendedMattressHeightMm', type: 'int', nullable: true, public: true },
        { name: 'mattressInsetMm', type: 'int', nullable: true, public: true },
        { name: 'mattressBase', type: 'text', nullable: true, public: true },
    ],
    ProductVariant: [
        { name: 'sourceSkuId', type: 'string', nullable: true, public: false },
        { name: 'sourceVariantUrl', type: 'string', length: 1024, nullable: true, public: false },
        { name: 'oldPrice', type: 'int', nullable: true, public: true },
        { name: 'finishLabel', type: 'string', nullable: true, public: true },
        { name: 'finishDescription', type: 'text', nullable: true, public: true },
        { name: 'upholsteryLabel', type: 'string', nullable: true, public: true },
        { name: 'upholsteryDescription', type: 'text', nullable: true, public: true },
        { name: 'profileLabel', type: 'string', nullable: true, public: true },
        { name: 'profileDescription', type: 'text', nullable: true, public: true },
    ],
};
